name: example-environment
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - numpy
  - matplotlib
  - tqdm
  - xarray
  - scikit-learn
  - pytorch
  - netcdf4
  - pip
  - pip:
    - gym
